import React, { useEffect, useMemo } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, X } from 'lucide-react';
import { InteractionPoint } from '../types';
import { getPedagogicalIssues } from '../utils/projectSafety';
interface Props { isOpen: boolean; interactions: InteractionPoint[]; videoDuration: number; onClose: () => void; onApprove: () => void; }
export const QualityReviewModal: React.FC<Props> = ({ isOpen, interactions, videoDuration, onClose, onApprove }) => {
  const issues = useMemo(() => getPedagogicalIssues(interactions, videoDuration), [interactions, videoDuration]);
  useEffect(() => { if (!isOpen) return; const fn = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', fn); return () => window.removeEventListener('keydown', fn); }, [isOpen, onClose]);
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4 backdrop-blur-md"><section role="dialog" aria-modal="true" aria-labelledby="quality-review-title" className="flex max-h-[88vh] w-full max-w-xl flex-col overflow-hidden rounded-3xl border border-white/10 bg-[#0c1728] shadow-2xl">
    <header className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300"><ClipboardCheck className="h-5 w-5" /></div><div><h2 id="quality-review-title" className="text-sm font-extrabold text-white">Rà soát trước khi xuất bản</h2><p className="text-[11px] text-slate-400">Kiểm tra logic, đáp án và mức độ hoàn thiện</p></div></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-white/5 hover:text-white" aria-label="Đóng rà soát"><X className="h-4 w-4" /></button></header>
    <div className="overflow-y-auto p-5">{issues.length === 0 ? <div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.07] p-4"><div className="flex items-center gap-2 text-sm font-bold text-emerald-200"><CheckCircle2 className="h-5 w-5" />Kịch bản đạt kiểm tra tự động</div><p className="mt-1 text-xs text-emerald-100/70">Các mốc thời gian, đáp án và nội dung bắt buộc đều hợp lệ.</p></div> : <div className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.06] p-4"><div className="flex items-center gap-2 text-sm font-bold text-amber-200"><AlertTriangle className="h-5 w-5" />Có {issues.length} điểm nên kiểm tra lại</div><ul className="mt-3 space-y-2 text-xs text-amber-100/75">{issues.map((issue, index) => <li key={`${issue}-${index}`} className="rounded-xl bg-black/10 px-3 py-2">{issue}</li>)}</ul></div>}</div>
    <footer className="flex flex-col-reverse gap-2 border-t border-white/[0.07] px-5 py-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-semibold text-slate-300 hover:bg-white/5">Quay lại chỉnh sửa</button><button type="button" onClick={onApprove} className="rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-2.5 text-xs font-bold text-white shadow-lg shadow-blue-950/50 hover:brightness-110">{issues.length ? 'Tôi đã rà soát, tiếp tục' : 'Xác nhận và tiếp tục'}</button></footer>
  </section></div>;
};
